from enum import Enum


class Action(str, Enum):
    DISCOVER = "DISCOVER"
    READ = "READ"
    WRITE = "WRITE"
    EXECUTE = "EXECUTE"
    ACCESS_CREDENTIAL = "ACCESS_CREDENTIAL"
    MOVE = "MOVE"
    REQUEST_RESOURCE = "REQUEST_RESOURCE"
    LEGITIMATE_TASK = "LEGITIMATE_TASK"


SUSPICIOUS_ACTIONS = {
    Action.ACCESS_CREDENTIAL,
    Action.MOVE,
}

